// Generates the D1 migration for Better Auth's tables from the SAME options the Worker uses
// (src/auth.ts), against a throwaway in-memory SQLite. Hand-writing that schema would drift
// the first time a plugin changes its columns.
//
//   npm run schema   ->  migrations/0001_better_auth.sql
//
// Runs under Node's built-in TypeScript stripping and node:sqlite (Node 23.6+).
import { DatabaseSync } from "node:sqlite";
import { writeFileSync } from "node:fs";
import { getMigrations } from "better-auth/db/migration";
import { authOptions } from "../src/auth.ts";

const options = {
  ...authOptions(new DatabaseSync(":memory:")),
  secret: "schema-generation-only-not-a-real-secret-0000",
  baseURL: "http://localhost",
};

const { compileMigrations } = await getMigrations(options);
const sql = await compileMigrations();

const header = `-- Generated by scripts/generate-schema.mjs from src/auth.ts. Do not edit by hand;\n-- change the auth options and regenerate instead.\n\n`;
writeFileSync(new URL("../migrations/0001_better_auth.sql", import.meta.url), header + sql.trim() + "\n");
console.log(sql);
